apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi
  labels:
    app: my-fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-fastapi
  template:
    metadata:
      labels:
        app: my-fastapi
    spec:
      containers:
      - name: my-fastapi
        image: rivallar/hw20:latest
        ports:
            - containerPort: 8088
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: CONFIGMAP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: username