apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruslan-project-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ruslan-rusanovich/CD_part.git
    targetRevision: HEAD
    path: kubernetes-deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true