apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.internalServiceName }}
spec:
  selector:
    app: {{ .Values.webAppName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.containerPort }}