apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.my-fastapi }}
  labels:
    app: {{ .Values.my-fastapi }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.my-fastapi }}
  template:
    metadata:
      labels:
        app: {{ .Values.my-fastapi }}
    spec:
      containers:
      - name: {{ .Values.my-fastapi }}
        image: {{ .Values.image }}
        ports:
            - containerPort: {{ .Values.containerPort }}